settings:
  username: "chimpdev"
  commit_msg: "Update recent activity"
  max_lines: 5
  readme_file: "./TEMPLATE.md"
  commit_name: "readme-bot"
  commit_email: "41898282+github-actions[bot]@users.noreply.github.com"
  line_prefix: "{NUM}. "
messages:
  added_member: "I became collaborator on {REPO}"
  changes_approved: "I approved changes in {ID} on {REPO}"
  changes_requested: "I requested {AMOUNT} change(s) in {ID} on {REPO}"
  comments: "I commented on {ID} in {REPO}"
  create_repo: "I created {REPO}"
  fork_repo: "I forked {FORK} from {REPO}"
  issue_opened: "I opened issue {ID} in {REPO}"
  issue_closed: "I closed issue {ID} in {REPO}"
  new_release: "I released {ID} in {REPO}"
  new_star: "I starred {REPO}"
  pr_opened: "I opened pull request {ID} in {REPO}"
  pr_closed: "I closed pull request {ID} in {REPO}"
  pr_merged: "I merged pull request {ID} in {REPO}"
  push: "I pushed {AMOUNT} commit(s) to {REPO}"
  wiki_create: "I created new wiki page {WIKI} in {REPO}"
