settings:
  username: "chimpdev"
  commit_msg: "Update recent activity"
  max_lines: 5
  readme_file: "./README.md"
  commit_name: "readme-bot"
  commit_email: "41898282+github-actions[bot]@users.noreply.github.com"
  line_prefix: "{NUM}. "
messages:
  added_member: "Became collaborator on {REPO}"
  changes_approved: "Approved changes in {ID} on {REPO}"
  changes_requested: "Requested {AMOUNT} change(s) in {ID} on {REPO}"
  comments: "Commented on {ID} in {REPO}"
  create_repo: "Created {REPO}"
  fork_repo: "Forked {FORK} from {REPO}"
  issue_opened: "Opened issue {ID} in {REPO}"
  issue_closed: "Closed issue {ID} in {REPO}"
  new_release: "Released {ID} in {REPO}"
  new_star: "Starred {REPO}"
  pr_opened: "Opened pull request {ID} in {REPO}"
  pr_closed: "Closed pull request {ID} in {REPO}"
  pr_merged: "Merged pull request {ID} in {REPO}"
  push: "Pushed {AMOUNT} commit(s) to {REPO}"
  wiki_create: "Created new wikpage {WIKI} in {REPO}"
